jobs:
  ci:
    name: Main
    runs-on: ubuntu-20.04

    steps:
      - name: Pull
        uses: actions/checkout@v2
      - name: Fetch Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Checks
        run: ./build/action

name: Build

on:
  schedule:
    - cron: "10 2/3 * * *"
